### ISSUE TITLE
Nvidia plugin crash

### ISSUE THREAD

**Issue by xxxserxxx** [xxxserxxx/gotop-nvidia#1]
v3.4.x candidate.  @talentlessguy reports:

```
17:56:17 cpu.go:30: GeForce GT 740M 0: strconv.Atoi: parsing "N/A": invalid syntax
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/xxxserxxx/gotop-nvidia.updateNvidiaMem(0xc0002da690, 0x0)
    /home/ser/workspace/gotop-nvidia/nvidia.go:53 +0x239
github.com/xxxserxxx/gotop/devices.UpdateMem(0xc0002da690)
    /home/ser/workspace/gotop/devices/mem.go:19 +0x84
github.com/xxxserxxx/gotop/widgets.NewMemWidget(0x3b9aca00, 0x7, 0xb79bdb)
    /home/ser/workspace/gotop/widgets/mem.go:29 +0x1c6
github.com/xxxserxxx/gotop/layout.makeWidget(0xc000026ee0, 0x19, 0xc000026ea0, 0x1e, 0xb7c238, 0xa, 0x7, 0x0, 0x0, 0x0, ...)
    /home/ser/workspace/gotop/layout/layout.go:170 +0xae
github.com/xxxserxxx/gotop/layout.processRow(0xc000026ee0, 0x19, 0xc000026ea0, 0x1e, 0xb7c238, 0xa, 0x7, 0x0, 0x0, 0x0, ...)
    /home/ser/workspace/gotop/layout/layout.go:117 +0x40e
github.com/xxxserxxx/gotop/layout.Layout(0xc00024c2a0, 0x4, 0x4, 0xc000026ee0, 0x19, 0xc000026ea0, 0x1e, 0xb7c238, 0xa, 0x7, ...)
    /home/ser/workspace/gotop/layout/layout.go:41 +0x184
main.main()
    /home/ser/workspace/gotop/cmd/gotop/main.go:403 +0x5ff
```

**Comment by xxxserxxx** [comment]
@talentlessguy If it has stopped crashing, I'd like to close this. If you're seeing a different issue (no values, etc) let's open a different ticket.

**Comment by talentlessguy** [comment]
@xxxserxxx NVIDIA plugin works perfectly fine on GTX1050 (modern GPU, compared to GT740M that had issues before as it lacked some sensors) so this can be closed

**Comment by xxxserxxx** [comment]
@talentlessguy thank you. I fixed another nvidia bug in the meantime and pushed out a new release against gotop v4.1.0.
